[project]
name = "wrapping-nft"
costs_version = 1

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.card]
path = "contracts/card.clar"
depends_on = []
